### PR TITLE
Controlled ramp-up of scenarios

### PR DESCRIPTION
**Pull request by rlefebvre**
Concurrency is handled by started `n` go-blocks simultaneously, all
blocking on the same timeout channel up-front, self-regulating
around the `concurrent-scenarios` atom.

This takes the ramp-up logic outside of the scenario go-block into
a single controller go-block, until the ramp-up period is over, leaving
individual scenarios to self-regulate thereon.

Issues: #53

### CODE REVIEW

**Comment by rlefebvre** [comment]
Here's a proposal to fix the issue with high-concurrency. This mitigates the problem of having all users initially block on the same timeout channel. Let me know if you like the approach, or anything you'd like me to change. Cheers!

**Comment by mhjort** [comment]
Great! I don't have time to look this in detail now. I will take a look next week.

**Comment by mhjort** [comment]
Are you able to reproduce the issue? Reading from `core.async` source I understand where the problem lies. However, I still cannot reproduce the issue with my laptop. I am guessing this happens more often with certain cpus. I have `Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz`.

Your solution could fix the problem. I am worried it complicates the implementation quite a bit. So one thing I am wondering now if it would make sense to remove the whole `timeout` there. Originally I added that one so that there wouldn't be a tight loop where concurrency distribution function is called over and over again without any sleeps. Maybe that is not real concern. Already tested with simple functions and that approach works well. What kind of concurrency distribution functions you've been using?

**Comment by rlefebvre** [comment]
I had the issue, which is why I looked into fixing this. I use it on windows on this CPU: `Processor	Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz, 3601 Mhz, 6 Core(s), 12 Logical Processor(s)`. The issue happens systematically when setting concurrency higher than 1024.

My `concurrency-distribution` function does a linear ramp-up and then stays at 1.0.

I agree this is fairly complex though. I am not expecting you to accept without giving some thought to the problem.

**Comment by mhjort** [comment]
Update related to this. I have found the root cause of this problem. Internally `core.async` uses cache for timeout channels. Therefore all takes in this case will use same channel instance. My idea is to create different version of `timeout` channel that should solve this issue by fixing the root cause.

**Comment by rlefebvre** [comment]
I thought that much was clear from the original issue (#53). How do you plan to go about creating different version of timeout channel ? As far as I know, the caching is done automatically at a 20ms resolution. This is why I opted for a single control loop that starts scenarios when they are needed. Seems like a better design to me. Thoughts ?

**Comment by mhjort** [comment]
Sorry. Miscommunication. Yes, it was clear already from the original issue that caching is the problem. But what I have found with my tests is that the ramp-up is not only place where this problem occurs once and a while when concurrency is high. `simulation.clj` has three places where `timeout` is used. What I am now after is to have a solution that fixes all of them.

The solution is in this PR https://github.com/mhjort/clj-gatling/pull/60. What do you think? 

Also I have now deployed version `0.14.0-beta` for testing this. This should be backwards compatible change but it might change performance of `clj-gatling`. So far I have not seen any performance implications but it might be good that other people try this out with their scenarios.

I have a plan to raise an issue about this to core.async Jira. However, I guess this is a rare use case for core.async and they won't be interested in changing anything there. But let's see...

**Comment by rlefebvre** [comment]
This thread and Tim Baldridge's feedback in particular is interesting:

https://groups.google.com/d/msg/clojure/OSwKOKEupGc/scDvYqyuuuAJ

My initial reaction is that if we reached this limit we must be doing something wrong. I think having all 'agents' block on timeouts simultaneously might not be the best design. But perhaps this is one case where it does make sense.

How/where did you get these errors other than in the initial rampup ? My guess was that with some real payload it would be unlikely/undesirable to have 'agents' unblock in sync so that would be an issue only when ramping up faster than 1024 per 20ms or at implausibly high concurrency levels.

I'm not against PR#60 as a fix if you prefer that. It will fix the issue as far as I am concern and allow testing at high enough levels. I didn't have a chance to test it yet though.

**Comment by mhjort** [comment]
Thanks. Good catch. I have to to check that thread.

**Comment by mhjort** [comment]
The new implementation of timeout channel fixes this issue: https://github.com/mhjort/clj-gatling/blob/master/src/clj_gatling/timers.clj

**Pull request closed without merging**
