### PR TITLE
Dynamic scenarios

### PR DESCRIPTION
**Pull request by rlefebvre**
As discussed in issue #48.

Hi! I am running load tests again and took time to organize the proposed fix. Sorry it took so long, I was pulled away on other projects.

### CODE REVIEW

**Comment by mhjort** [comment]
Looks great! Could you also add a test case for this in `simulation_test.clj`?

**Comment by mhjort** [comment]
One thing I noticed. If for some reason `step-fn`does not return nil the tests won't stop ever. It would be better if `clj-gatling` obeys duration or request count always. Even in case there is a bug in `step-fn` and it does not return `nil`.

**Comment by rlefebvre** [comment]
I've added a basic test for step-fn. Will fix to obey duration or request count later this week.

**Comment by mhjort** [comment]
Looks good. Actually it works as expected now. I forgot that there is a separate ` :allow-early-termination?` option that can be turned on. With that option it behaves as it should. Even when `step-fn` does not return nil ever the simulation finishes 

I will merge this and add a note to documentation that you should use that `:allow-early-termination?` option if you want to be sure that scenario always exits when using `step-fn`.

**Pull request merged**
