### PR TITLE
Feature/accept user defined output writers

### PR DESCRIPTION
**Pull request by mhjort**

### CODE REVIEW

**Comment by aidylewis** [comment]
I was thinking something like this would produce no reports, but highcharts are still created.

```clojure
 {:concurrency 10                                                                                                                                   
   :reporter {:writer (fn [_ _ _]) :generator (fn [_])}})
```

**Comment by mhjort** [comment]
Did you try with new simulation format introduced with 0.8 version?

**Comment by mhjort** [comment]
Just updated clj-gatling-example project on how to skip reports if you want to take a look.

**Comment by aidylewis** [comment]
That runs great. Thanks.

**Pull request merged**
